export const DEFAULT_TIME_LINE_SCALE_COEFFICIENT = 400;
export const MIN_TIME_LINE_SCALE_COEFFICIENT = 10;
export const MAX_TIME_LINE_SCALE_COEFFICIENT = 5000;

export const WAVE_FORM_HEIGHT = 200;
export const DEFAULT_WAVE_FORM_WIDTH = '100%';
export const DEFAULT_WAVE_FORM_COLOR = 'violet';
