export const DEFAULT_TIME_LINE_SCALE_COEFFICIENT = 400;
export const MIN_TIME_LINE_SCALE_COEFFICIENT = 100;
export const TIME_LINE_SCALE_COEFFICIENT_STEP = 100;
export const MAX_TIME_LINE_SCALE_COEFFICIENT = 5000;

export const WAVE_FORM_HEIGHT = 200;
export const DEFAULT_WAVE_FORM_WIDTH = '100%';
export const DEFAULT_WAVE_FORM_COLOR = 'violet';
