name: Github Pages deploy

on:
  push:
    branches: []
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install -g corepack@0.31.0
          corepack enable
          yarn install

      - name: Pre-deploy
        run: yarn predeploy

      - name: Deploy
        run: yarn deploy
